spring.application.name=campus-used-books

# 開啟 H2 的網頁版控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 資料庫連線設定 (記憶體模式，資料庫名稱叫 usedbooks)
spring.datasource.url=jdbc:h2:mem:usedbooks
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 讓 Spring Boot 啟動時自動幫你管理資料表
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB